#Run this workflow every 1 mi
name: Rollout Percentage

on:
  push:

jobs:
  rollout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve integer from cache
        uses: actions/cache@v3
        with:
          path: |
            percentage.txt
          key: percentageTestKey

      - name: Print env variables
        run: |
            echo "BETA_ROLL_OUT_PERCENTAGE=$(head percentage.txt)" >> $GITHUB_ENV

      - name: Add env variables
        run:  |
          echo "Previous content of percentage.txt"
          cat percentage.txt
          echo heloooooooo > percentage.txt
          echo "New content of percentage.txt"
          cat percentage.txt

      - name: Save integer to cache
        uses: actions/cache@v3
        with:
          path: |
              percentage.txt
          key: percentageTestKey
