name: Workflow 2

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get input
        run: |
          echo "My integer is $(cat percentage.txt)"
        shell: bash
