name: Workflow 1

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set output
        run: echo "::set-output name=my_integer::123"
        shell: bash
        env:
          MY_EVENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
      - name: Save output
        run: |
          echo $MY_EVENT_PAYLOAD > my_output.txt
        shell: bash

      - name: Create commits
        run: |
            git config user.name 'github-actions'
            git config user.email 'github-actions@github.com'
            echo 50 >> percentage.txt
            git add .
            git commit --no-verify -am "[ROID-1560][github] Added Build"
            git push --no-verify
