name: Workflow 1

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        run: echo "::set-output name=my_integer::123"
        shell: bash
        env:
          MY_EVENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
      - name: Save output
        run: |
          echo $MY_EVENT_PAYLOAD > my_output.txt
        shell: bash
